# Identify usages of count on an Enumerable that follow calls to select or  reject.
# Querying logic can instead be passed to the count call.
Performance/Count:
  Enabled: true

# Checks for uses of `each_key` & `each_value` Hash methods.
Performance/HashEachMethods:
  Enabled: true

# Identifies places where Hash#merge! can be replaced by Hash#[]=.
Performance/RedundantMerge:
  Enabled: true

# Identify usages of count on an Array and Hash and change them to size.
Performance/Size:
  Enabled: true

# This cop identifies places where `gsub` can be replaced by `tr` or `delete`.
Performance/StringReplacement:
  Enabled: true

# Checks for .times.map calls. In most cases such calls can be replaced with an explicit array creation.
Performance/TimesMap:
  Enabled: true
