require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/anthony-robin/rubocop-rules/master/.rubocop-custom.yml
  - https://raw.githubusercontent.com/anthony-robin/rubocop-rules/master/.rubocop-disabled.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'lib/generators/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true
